language: python
python:
  - "2.7"
services:
  - redis-server
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libleveldb-dev
install: make setup
env:
  - TEST_SUITE=fulltests BACKEND="--backend memory"
  - TEST_SUITE=fulltests BACKEND="--backend lmdb"
  - TEST_SUITE=fulltests BACKEND="--backend leveldb"
  - TEST_SUITE=fulltests-real-redis
script: make $TEST_SUITE
